# Generated by Django 4.0.1 on 2022-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=30)),
                ('coursefees', models.IntegerField(max_length=30)),
                ('trainer', models.CharField(max_length=30)),
                ('hours', models.IntegerField(max_length=30)),
            ],
        ),
    ]
