# Generated by Django 4.0.1 on 2022-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminusername', models.CharField(max_length=30)),
                ('adminpassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='coursefees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
